// Generated by delombok at Thu Jun 14 14:59:06 CEST 2018
package jigsawtest.mapInto;

import java.util.List;

public class PersonLite {
  private String forename;
  private String lastname;
  private List<AddressLite> addresses;


  @SuppressWarnings("all")
  public static class PersonLiteBuilder {
    @SuppressWarnings("all")
    private String forename;
    @SuppressWarnings("all")
    private String lastname;
    @SuppressWarnings("all")
    private List<AddressLite> addresses;

    @SuppressWarnings("all")
    PersonLiteBuilder() {
    }

    @SuppressWarnings("all")
    public PersonLiteBuilder forename(final String forename) {
      this.forename = forename;
      return this;
    }

    @SuppressWarnings("all")
    public PersonLiteBuilder lastname(final String lastname) {
      this.lastname = lastname;
      return this;
    }

    @SuppressWarnings("all")
    public PersonLiteBuilder addresses(final List<AddressLite> addresses) {
      this.addresses = addresses;
      return this;
    }

    @SuppressWarnings("all")
    public PersonLite build() {
      return new PersonLite(forename, lastname, addresses);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "PersonLite.PersonLiteBuilder(forename=" + this.forename + ", lastname=" + this.lastname + ", addresses=" + this.addresses + ")";
    }
  }

  @SuppressWarnings("all")
  public static PersonLiteBuilder builder() {
    return new PersonLiteBuilder();
  }

  @SuppressWarnings("all")
  public PersonLite() {
  }

  @SuppressWarnings("all")
  public PersonLite(final String forename, final String lastname, final List<AddressLite> addresses) {
    this.forename = forename;
    this.lastname = lastname;
    this.addresses = addresses;
  }

  @SuppressWarnings("all")
  public String getForename() {
    return this.forename;
  }

  @SuppressWarnings("all")
  public String getLastname() {
    return this.lastname;
  }

  @SuppressWarnings("all")
  public List<AddressLite> getAddresses() {
    return this.addresses;
  }

  @SuppressWarnings("all")
  public void setForename(final String forename) {
    this.forename = forename;
  }

  @SuppressWarnings("all")
  public void setLastname(final String lastname) {
    this.lastname = lastname;
  }

  @SuppressWarnings("all")
  public void setAddresses(final List<AddressLite> addresses) {
    this.addresses = addresses;
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof PersonLite)) return false;
    final PersonLite other = (PersonLite) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$forename = this.getForename();
    final Object other$forename = other.getForename();
    if (this$forename == null ? other$forename != null : !this$forename.equals(other$forename)) return false;
    final Object this$lastname = this.getLastname();
    final Object other$lastname = other.getLastname();
    if (this$lastname == null ? other$lastname != null : !this$lastname.equals(other$lastname)) return false;
    final Object this$addresses = this.getAddresses();
    final Object other$addresses = other.getAddresses();
    if (this$addresses == null ? other$addresses != null : !this$addresses.equals(other$addresses)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof PersonLite;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $forename = this.getForename();
    result = result * PRIME + ($forename == null ? 43 : $forename.hashCode());
    final Object $lastname = this.getLastname();
    result = result * PRIME + ($lastname == null ? 43 : $lastname.hashCode());
    final Object $addresses = this.getAddresses();
    result = result * PRIME + ($addresses == null ? 43 : $addresses.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "PersonLite(forename=" + this.getForename() + ", lastname=" + this.getLastname() + ", addresses=" + this.getAddresses() + ")";
  }
}
